export enum PolicyDocumentType {
  CODE_OF_CONDUCT = 'CODE_OF_CONDUCT',
  DATA_PRIVACY_POLICY = 'DATA_PRIVACY_POLICY',
  IT_SECURITY_POLICY = 'IT_SECURITY_POLICY',
  REMOTE_WORK_POLICY = 'REMOTE_WORK_POLICY',
  ONBOARDING = 'ONBOARDING',
  PERFORMANCE = 'PERFORMANCE',
  LEAVE = 'LEAVE',
  EMPLOYEE_HANDBOOK = 'EMPLOYEE_HANDBOOK'
}

export enum PolicyDocumentParentId {
  POLICY = 'POLICY',
  HR = 'HR',
  SALES = 'SALES',
  MARKETING = 'MARKETING',
  ENGINEERING = 'ENGINEERING',
  PRODUCT = 'PRODUCT',
  OPS = 'OPS',
  FINANCE = 'FINANCE',
  LEGAL = 'LEGAL',
  OTHER = 'OTHER'
}
